name: learn-github-actions
on: [ push ]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: Xotabu4/selenoid-github-action@v2
      - run: ./gradlew clean test -v -Dselenide.remote=http://localhost:4444/wd/hub