name: learn-github-actions
on: [ push ]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: Xotabu4/selenoid-github-action@v2
      - run: ./gradlew clean test -v -Dselenide.remote=http://localhost:4444/wd/hub
               - uses: actions/checkout@v2
               if: always()
               continue-on-error: true
               with:
                 ref: gh-pages
                 path: gh-pages
                 # генерируем отчет
      - uses: simple-elf/allure-report-action@master
        if: always()
        with:
           gh_pages: gh-pages
           allure_results: build/allure-results
           allure_report: allure-report
           allure_history: allure-history
       # публикуем отчет
      - uses: peaceiris/actions-gh-pages@v2
        if: always()
        env:
         PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         PUBLISH_BRANCH: gh-pages
         PUBLISH_DIR: allure-history